name: ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
       
      - name: Install dependencies
        run: npm install

      - name: Build colision-detector
        run: npm run build
        working-directory: ./packages/tiled-colision-detector
        
      - name: Build tiled-map
        run: npm run build
        working-directory: ./packages/tiled-map

      - name: Build map-editor
        run: npm run build
        working-directory: ./packages/map-editor

      - name: Test tiled-map
        run: npm test
        working-directory: ./packages/tiled-map

      - name: Test map-editor
        run: npm test
        working-directory: ./packages/map-editor
